# Generated by Django 4.1.6 on 2023-03-05 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tutorme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "student"), (2, "tutor")], default=1
            ),
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=150)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutorme.appuser",
                    ),
                ),
            ],
        ),
    ]
