# Generated by Django 4.1.6 on 2023-03-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tutorme", "0002_alter_appuser_user_type_tutor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=150)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "pending"), (2, "accepted"), (3, "declined")],
                        default=1,
                    ),
                ),
                (
                    "from_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_student",
                        to="tutorme.appuser",
                    ),
                ),
                (
                    "to_tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_tutor",
                        to="tutorme.appuser",
                    ),
                ),
            ],
        ),
    ]
