# Generated by Django 4.1.6 on 2023-03-06 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorme", "0003_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 3, 6, 0, 22, 58, 433154, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
