# Generated by Django 4.1.6 on 2023-03-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0005_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='review',
            field=models.CharField(default='', max_length=500),
        ),
    ]
