# Generated by Django 4.1.6 on 2023-04-01 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0007_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_requested',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='request',
            name='end_time_requested',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='request',
            name='start_time_requested',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
