# Generated by Django 4.1.6 on 2023-04-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0008_request_date_requested_request_end_time_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='bio',
            field=models.TextField(default="Hi, I'm a tutor!"),
        ),
    ]
