# Generated by Django 4.1.6 on 2023-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0009_tutor_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='bio',
        ),
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.TextField(default="Hi, I'm excited to use TutorMe!"),
        ),
    ]
