# Generated by Django 4.1.6 on 2023-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0010_remove_tutor_bio_appuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='help_description',
            field=models.TextField(default='I am looking for a tutor'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='year',
            field=models.CharField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Graduate')], default=1, max_length=12),
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
