# Generated by Django 4.1.6 on 2023-04-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0011_appuser_help_description_appuser_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
