# Generated by Django 4.1.6 on 2023-04-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0012_delete_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='available_times',
            field=models.JSONField(default=dict),
        ),
    ]
