# Generated by Django 4.1.6 on 2023-04-12 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0013_tutor_available_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='available_times',
        ),
        migrations.CreateModel(
            name='TutorTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_times', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorme.appuser')),
            ],
        ),
    ]
