# Generated by Django 4.1.6 on 2023-04-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0015_alter_request_end_time_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutortimes',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
