# Generated by Django 4.1.6 on 2023-04-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0016_tutortimes_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='help_description',
            field=models.TextField(default='I am looking for a tutor'),
        ),
    ]
